services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.24.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    - ./backups:/backups
    restart: on-failure:0
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai,backup-filesystem
      - CLUSTER_HOSTNAME=node1
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - BACKUP_FILESYSTEM_PATH=/backups
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDEVMODE=1
      - WEAVIATE_API_KEY=none
      - WEAVIATE_URL=http://weaviate:8080/
      - WEAVIATE_ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - weaviate
    working_dir: /app/demo_app
    command: uvicorn app.server:app --host 0.0.0.0 --port 8000

volumes:
  weaviate_data:
